In [2]:
import pandas as pd
import numpy as np

In [3]:
# loading all the three datasets

citi_1=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\202608-citibike-tripdata_1.csv")
citi_2=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\202608-citibike-tripdata_2.csv")
citi_3=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\202608-citibike-tripdata_3.csv")

station=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\station_information.csv")
weather=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\nyc_weather.csv")

C:\Users\vaish\AppData\Local\Temp\ipykernel_26852\4292091360.py:3: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  citi_1=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\202608-citibike-tripdata_1.csv")
C:\Users\vaish\AppData\Local\Temp\ipykernel_26852\4292091360.py:4: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  citi_2=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\202608-citibike-tripdata_2.csv")
C:\Users\vaish\AppData\Local\Temp\ipykernel_26852\4292091360.py:5: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  citi_3=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\CitiBike_Project\\data\\raw_dataset\\202608-citibike-tripdata_3.csv")

In [4]:
# combining the 3 cities datset into the one

comb_citi=pd.concat([citi_1,citi_2,citi_3],ignore_index=True)

comb_citi

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,60D4C98548B9AD05,electric_bike,2026-08-18 09:41:00.056,2026-08-18 10:08:39.527,Grand Ave & W Fordham Rd,8571.02,E 182 St & Grand Concourse,8494.07,40.862880,-73.903160,40.855910,-73.900510,member
2999996,B09E12D4908CCBA8,classic_bike,2026-08-24 05:42:09.563,2026-08-24 05:46:14.180,5 Ave & E 30 St,6248.08,W 36 St & 7 Ave,6483.06,40.745985,-73.986295,40.752149,-73.989539,member
2999997,EDB190CC044419C4,electric_bike,2026-08-16 01:24:54.216,2026-08-16 01:30:32.323,25 Ave & 41 St,6943.07,24 Ave & 26 St,7152.10,40.767666,-73.910963,40.774591,-73.918544,member
2999998,483C962E21C61F35,electric_bike,2026-08-17 23:34:45.472,2026-08-17 23:40:49.561,W 34 St & Hudson Blvd E,6535.04,W 36 St & 7 Ave,6483.06,40.755167,-74.000599,40.752149,-73.989539,member
2999999,25DC3F883F354854,electric_bike,2026-08-26 05:48:38.439,2026-08-26 05:56:56.491,E 115 St & Lexington Ave,7599.09,Lenox Ave & W 144 St,7910.01,40.797911,-73.942300,40.819783,-73.936521,member

In [5]:
print(comb_citi.columns)
print(weather.columns)
print(station.columns)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')
Index(['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation',
       'wind_speed_10m'],
      dtype='str')
Index(['station_id', 'name', 'short_name', 'lon', 'lat', 'region_id',
       'capacity', 'rental_uris', 'rental_methods', 'has_kiosk',
       'station_type', 'external_id', 'electric_bike_surcharge_waiver',
       'eightd_station_services', 'eightd_has_key_dispenser'],
      dtype='str')

In [6]:
print(comb_citi.shape)
print(weather.shape)
print(station.shape)

(3000000, 13)
(744, 5)
(2520, 15)

## Citites cleaning

In [7]:
# to combine the datasets merging the similar columns in the three dataset 
# converting the columns into datetime fromat

comb_citi["started_at"]=pd.to_datetime(comb_citi["started_at"])
comb_citi["started_at"]

comb_citi["ended_at"]=pd.to_datetime(comb_citi["ended_at"])
comb_citi["ended_at"]

weather["time"]=pd.to_datetime(weather["time"])
weather["time"]

0     2026-08-01 00:00:00
1     2026-08-01 01:00:00
2     2026-08-01 02:00:00
3     2026-08-01 03:00:00
4     2026-08-01 04:00:00
              ...
739   2026-08-31 19:00:00
740   2026-08-31 20:00:00
741   2026-08-31 21:00:00
742   2026-08-31 22:00:00
743   2026-08-31 23:00:00
Name: time, Length: 744, dtype: datetime64[us]

In [8]:
# calculatiio of the comb_citi duration in minutes
comb_citi["ride_duration_min"]=(comb_citi["ended_at"]-comb_citi["ended_at"]).dt.total_seconds()/60

In [9]:
# removing the inavlid rides

# comb_citi=comb_citi[(comb_citi["ride_duration_min"]>1)&(comb_citi["ride_duration_min"]<24*60)]

In [10]:
# removing the duplicates
comb_citi["ride_id"]=comb_citi["ride_id"].drop_duplicates()

comb_citi["ride_id"].duplicated().sum()

np.int64(0)

In [11]:
print("Final Shape: ",comb_citi.shape)

Final Shape:  (3000000, 14)

In [12]:
comb_citi

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration_min
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member,0.0
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member,0.0
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member,0.0
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,0.0
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,60D4C98548B9AD05,electric_bike,2026-08-18 09:41:00.056,2026-08-18 10:08:39.527,Grand Ave & W Fordham Rd,8571.02,E 182 St & Grand Concourse,8494.07,40.862880,-73.903160,40.855910,-73.900510,member,0.0
2999996,B09E12D4908CCBA8,classic_bike,2026-08-24 05:42:09.563,2026-08-24 05:46:14.180,5 Ave & E 30 St,6248.08,W 36 St & 7 Ave,6483.06,40.745985,-73.986295,40.752149,-73.989539,member,0.0
2999997,EDB190CC044419C4,electric_bike,2026-08-16 01:24:54.216,2026-08-16 01:30:32.323,25 Ave & 41 St,6943.07,24 Ave & 26 St,7152.10,40.767666,-73.910963,40.774591,-73.918544,member,0.0
2999998,483C962E21C61F35,electric_bike,2026-08-17 23:34:45.472,2026-08-17 23:40:49.561,W 34 St & Hudson Blvd E,6535.04,W 36 St & 7 Ave,6483.06,40.755167,-74.000599,40.752149,-73.989539,member,0.0
2999999,25DC3F883F354854,electric_bike,2026-08-26 05:48:38.439,2026-08-26 05:56:56.491,E 115 St & Lexington Ave,7599.09,Lenox Ave & W 144 St,7910.01,40.797911,-73.942300,40.819783,-73.936521,member,0.0

## Station Cleaning

In [13]:
station.columns

Index(['station_id', 'name', 'short_name', 'lon', 'lat', 'region_id',
       'capacity', 'rental_uris', 'rental_methods', 'has_kiosk',
       'station_type', 'external_id', 'electric_bike_surcharge_waiver',
       'eightd_station_services', 'eightd_has_key_dispenser'],
      dtype='str')

In [14]:
# removing the unecessary columns

# station.drop("short_name",axis=1,inplace=True)
# station.drop("region_id",axis=1,inplace=True)
# station.drop("rental_uris",axis=1,inplace=True)
# station.drop("rental_methods",axis=1,inplace=True)
# station.drop("has_kiosk",axis=1,inplace=True)
# station.drop("station_type",axis=1,inplace=True)
# station.drop("external_id",axis=1,inplace=True)
# station.drop("electric_bike_surcharge_waiver",axis=1,inplace=True)
# station.drop("eightd_station_services",axis=1,inplace=True)
# station.drop("eightd_has_key_dispenser",axis=1,inplace=True)

In [15]:
station = station[['station_id', 'name', 'lat', 'lon', 'capacity']].copy()

In [16]:
station.columns

Index(['station_id', 'name', 'lat', 'lon', 'capacity'], dtype='str')

In [17]:
comb_citi['start_station_id'] = comb_citi['start_station_id'].astype(str).str.strip()
comb_citi['end_station_id'] = comb_citi['end_station_id'].astype(str).str.strip()

station['station_id'] = station['station_id'].astype(str).str.strip()

In [18]:
# renaming the column names accoriding to the citit daatset
station=station.rename(columns={
    "name":"station_name",
    "lat":"latitude",
    "lon":'longitude'
})
station.columns

Index(['station_id', 'station_name', 'latitude', 'longitude', 'capacity'], dtype='str')

#### Merging the station and comb citi datasets

In [19]:
# start station merge

comb_citi=comb_citi.merge(
    station,
    left_on="start_station_id",
    right_on="station_id",
    how="left"
)

In [20]:
# renaming the start comb citi datse columns

comb_citi=comb_citi.rename(columns={
    "station_name":"start_station_name",
    "latitude":"start_lat_station",
    "longitude":"start_lng_station",
    "capacity":"start_capacity"
})

In [21]:
# drop unwanted column from comb citi
comb_citi=comb_citi.drop(columns=["station_id"])

In [22]:
comb_citi=comb_citi.merge(
    station,
    left_on="end_station_id",
    right_on="station_id",
    how="left"
)

In [23]:
# renaming the end comb citi datse columns

comb_citi=comb_citi.rename(columns={
    "station_name":"end_station_name",
    "latitude":"end_lat_station",
    "longitude":"end_lng_station",
    "capacity":"end_capacity"
})

In [24]:
# drop unwanted column from comb citi
comb_citi=comb_citi.drop(columns=["station_id"])

In [25]:
comb_citi

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,ride_duration_min,start_station_name,start_lat_station,start_lng_station,start_capacity,end_station_name,end_lat_station,end_lng_station,end_capacity
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,60D4C98548B9AD05,electric_bike,2026-08-18 09:41:00.056,2026-08-18 10:08:39.527,Grand Ave & W Fordham Rd,8571.02,E 182 St & Grand Concourse,8494.07,40.862880,-73.903160,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999996,B09E12D4908CCBA8,classic_bike,2026-08-24 05:42:09.563,2026-08-24 05:46:14.180,5 Ave & E 30 St,6248.08,W 36 St & 7 Ave,6483.06,40.745985,-73.986295,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999997,EDB190CC044419C4,electric_bike,2026-08-16 01:24:54.216,2026-08-16 01:30:32.323,25 Ave & 41 St,6943.07,24 Ave & 26 St,7152.10,40.767666,-73.910963,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999998,483C962E21C61F35,electric_bike,2026-08-17 23:34:45.472,2026-08-17 23:40:49.561,W 34 St & Hudson Blvd E,6535.04,W 36 St & 7 Ave,6483.06,40.755167,-74.000599,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999999,25DC3F883F354854,electric_bike,2026-08-26 05:48:38.439,2026-08-26 05:56:56.491,E 115 St & Lexington Ave,7599.09,Lenox Ave & W 144 St,7910.01,40.797911,-73.942300,...,member,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Merge with the weather dataset

In [26]:
# prepare for erging weather dataset

weather["time"]=pd.to_datetime(weather["time"])
weather["date_hour"]=weather["time"].dt.floor("h")

In [27]:
# preparing the comb_citi dataset
comb_citi["date_hour"]=comb_citi["started_at"].dt.floor("h")

In [28]:
# Merging the datasets

final_df=comb_citi.merge(weather,
                         on="date_hour",
                         how="left")

In [29]:
final_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_station_name,end_lat_station,end_lng_station,end_capacity,date_hour,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,NaN,NaN,NaN,NaN,2026-08-10 14:00:00,2026-08-10 14:00:00,32.6,40.0,0.0,11.1
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,NaN,NaN,NaN,NaN,2026-08-10 08:00:00,2026-08-10 08:00:00,23.6,72.0,0.0,1.3
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,NaN,NaN,NaN,NaN,2026-08-08 19:00:00,2026-08-08 19:00:00,27.6,76.0,0.0,9.1
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,NaN,NaN,NaN,NaN,2026-08-05 14:00:00,2026-08-05 14:00:00,27.1,61.0,0.0,8.6
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,NaN,NaN,NaN,NaN,2026-08-01 14:00:00,2026-08-01 14:00:00,29.6,47.0,0.3,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,60D4C98548B9AD05,electric_bike,2026-08-18 09:41:00.056,2026-08-18 10:08:39.527,Grand Ave & W Fordham Rd,8571.02,E 182 St & Grand Concourse,8494.07,40.862880,-73.903160,...,NaN,NaN,NaN,NaN,2026-08-18 09:00:00,2026-08-18 09:00:00,24.4,91.0,0.1,2.1
2999996,B09E12D4908CCBA8,classic_bike,2026-08-24 05:42:09.563,2026-08-24 05:46:14.180,5 Ave & E 30 St,6248.08,W 36 St & 7 Ave,6483.06,40.745985,-73.986295,...,NaN,NaN,NaN,NaN,2026-08-24 05:00:00,2026-08-24 05:00:00,17.4,90.0,0.0,4.1
2999997,EDB190CC044419C4,electric_bike,2026-08-16 01:24:54.216,2026-08-16 01:30:32.323,25 Ave & 41 St,6943.07,24 Ave & 26 St,7152.10,40.767666,-73.910963,...,NaN,NaN,NaN,NaN,2026-08-16 01:00:00,2026-08-16 01:00:00,21.9,82.0,0.0,2.3
2999998,483C962E21C61F35,electric_bike,2026-08-17 23:34:45.472,2026-08-17 23:40:49.561,W 34 St & Hudson Blvd E,6535.04,W 36 St & 7 Ave,6483.06,40.755167,-74.000599,...,NaN,NaN,NaN,NaN,2026-08-17 23:00:00,2026-08-17 23:00:00,23.4,91.0,0.0,0.9
2999999,25DC3F883F354854,electric_bike,2026-08-26 05:48:38.439,2026-08-26 05:56:56.491,E 115 St & Lexington Ave,7599.09,Lenox Ave & W 144 St,7910.01,40.797911,-73.942300,...,NaN,NaN,NaN,NaN,2026-08-26 05:00:00,2026-08-26 05:00:00,17.6,87.0,0.0,5.7

## feature eng

In [30]:
# Time

final_df["hour"]=final_df["started_at"].dt.hour
final_df["day_of_week"]=final_df["started_at"].dt.day_name()
final_df["is_weekend"]=final_df["started_at"].dt.dayofweek >=5

In [31]:
# /trip distance

def haversine(lat1, lon1, lat2, lon2):
    R = 6371 # km
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

final_df['trip_distance_km'] = haversine(
final_df['start_lat'], final_df['start_lng'],
final_df['end_lat'], final_df['end_lng']
)

In [33]:
# saving the cleaned dataset

final_df.to_csv("citibike_final_cleaned.csv",index=False)